### ISSUE TITLE
excause me ,how can i use it in cocos creator??

### ISSUE THREAD

**Issue by exe19890522** [Timur310/PixelPlanets#2]
I want to use it in a universe game to save some random planets。
i want to know the out.js is can be used ?
what is the api?

**Comment by Timur310** [comment]
Hi! the project itself uses THREE.js to render 3D, out.js is a bundled version which you can import to html trough script tag, to bundle index.js which is an example scene you can use esbuild.There is also a server-side example where the code shows how to save images of planets, there is no usefull API right now, but you can see the layers folder to see how each planet is built up on 3D planes from three.js in each layer, hope it makes some sense :) or you can just use the original application which is running on the web, it's in the readme last part
