### ISSUE TITLE
[Question] Object-oriented classes - will they be added?

### ISSUE THREAD

**Issue by KurtLa** [Timur310/PixelPlanets#3]
Hi,
i consider your package for using in a flutter environment.

Do you think
+ Object-oriented classes for procedural planets
will be added in future?

**Comment by Timur310** [comment]
Hi! thank you for the question, currently I'm working on this on my free time and the project is on pause currently, you can see all the changes on the feat/typescript branch, my current goal is to port the project to typescript and make it Object-oriented at the same time, while it's not finished and not fully tested, you can see some example or even use he branch yourself, some base class is already created for example

**Comment by KurtLa** [comment]
Hi @Timur310 , thanks for your quick reply!
I've seen the ts branch and it sounds like a great improvement. Unfortunately Flutter can't run TypeScript, only JS engines are around :(

I'm preparing a game at the moment and I'm in the phase of choosing technologies. I would like to integrate the generators into the app so I don't have to download sprites for a randomly generated level.

Do you consider the js branch as discontinued or do you wish to have contributions/pull requests if I decide to use your package? Maybe my changes could lead to a different usage than the ts implementation.

**Comment by Timur310** [comment]
Hi @KurtLa  I'm open to all kind of impovement/contribution :) especially if it's benefits the users who uses the project, the js branch will not be deleted when the typescript port is finished if there is a need for it.So contributions and PRs are very welcomed, the typescript port is not fully finished so it's easy to adapt the master branch any time if a new feature is merged.Building/bundling the typescript version is also on my list after finalizing the port which will be helpfull for js only projects

**Comment by KurtLa** [comment]
Hey @Timur310 thanks, I really appreciate it. I will consider using your project. Thank you very much. Have a fantastic new year.
